export {
  getAutoConnect,
  getAutoReconnect,
  getDeviceId,
  getLastNodeId,
  getSplitApps,
  initAutoStartDefault,
  isAutoStartEnabled,
  setAutoConnect,
  setAutoReconnect,
  setAutoStart,
  setDeviceId,
  setLastNodeId,
  setManuallyDisconnected,
  setSplitApps,
  wasManuallyDisconnected,
} from './app-settings';
