import { z } from 'zod';

export const apiErrorCodeSchema = z.enum([
  'INTERNAL_ERROR',
  'VALIDATION_FAILED',
  'UNAUTHORIZED',
  'FORBIDDEN',

  'PAYMENT_REQUIRED',
  'PAYMENT_FAILED',
  'PLAN_CHANGE_LOCKED',
  'RECURRING_UNAVAILABLE',
  'PAYMENT_METHOD_MISSING',
  'WEBHOOK_INVALID',

  'NODE_NOT_FOUND',
  'NODE_UNAVAILABLE',
  'TUNNEL_FAILED',
]);
