import { z } from 'zod';

export const apiErrorCodeSchema = z.enum([
  'INTERNAL_ERROR',
  'VALIDATION_FAILED',
  'UNAUTHORIZED',
  'FORBIDDEN',
  'NOT_FOUND',
  'CONFLICT',

  'PAYMENT_REQUIRED',
  'PAYMENT_FAILED',
  'PLAN_CHANGE_LOCKED',
  'RECURRING_UNAVAILABLE',
  'PAYMENT_METHOD_MISSING',
  'WEBHOOK_INVALID',

  'NODE_NOT_FOUND',
  'NODE_UNAVAILABLE',
  'CONFIG_LIMIT_REACHED',
  'DEVICE_LIMIT_REACHED',
  'SUBSCRIPTION_REQUIRED',
  'EXTRA_DEVICES_LIMIT'
]);
