export {
  CACHE_TTL_MS,
  EXTENSION_TO_PLATFORM,
  GITHUB_RELEASE_URL,
  GITHUB_TIMEOUT_MS,
  githubAssetUrl,
  PLATFORM_EXTENSION_PRIORITY,
  UPDATER_ARCHIVE_SUFFIX,
  UPDATER_SIGNATURE_SUFFIX,
  UPDATER_TARGET,
} from './release.config';
