export { KEYBOARD_ROWS } from './keyboard.config';
export {
  HTTPS_PREFIX,
  LANGUAGE_BUTTONS,
  LINK_CODE_ALPHABET,
  LINK_CODE_LENGTH,
  LINK_CODE_TTL_MINUTES,
  LOCALE_CALLBACK_PREFIX,
  PLAN_CALLBACK_PREFIX,
  TELEGRAM_SECRET_HEADER,
  TRAILING_SLASH,
  WEBHOOK_PATH
} from './telegram.config';
export { BOT_BUTTONS, BOT_COMMANDS, BOT_LOCALES, BOT_PROFILE, BOT_TEXT, DEFAULT_BOT_LOCALE } from './telegram.messages';
