export {
  INCY_DEEP_LINK_NAME,
  SUBSCRIPTION_CONTENT_TYPE,
  SUBSCRIPTION_PEER_NAME,
  SUBSCRIPTION_PROFILE_TITLE,
  SUBSCRIPTION_SORT_ORDER,
  SUBSCRIPTION_TOKEN_BYTES,
  SUBSCRIPTION_UPDATE_INTERVAL_HOURS,
  SUBSCRIPTION_USERINFO_HIDDEN,
  VLESS_NAME_SUFFIX
} from './subscription-link.config';
