import { cpSync, existsSync, mkdirSync, readdirSync, rmSync } from 'node:fs';
import { join } from 'node:path';

// Written into jniLibs by cargo rather than copied from the overlay, so the
// cleanup below must leave it alone.
const CARGO_LIB = 'libgnomevpn_lib.so';

// Generated by `tauri android init` and not part of the overlay.
const GENERATED_SOURCES = [];

const removeStale = ({ directory, keep }) => {
  const removed = [];

  for (const entry of readdirSync(directory)) {
    if (!keep(entry)) {
      rmSync(join(directory, entry), { recursive: true });
      removed.push(entry);
    }
  }

  return removed;
};

// A binary renamed in the overlay leaves its predecessor behind in jniLibs,
// where it still ships inside the APK — libxray.so outlived the move to
// hysteria that way, and the tunnel failed at runtime looking for a name the
// APK no longer carried.
export const copyLibs = ({ from, to }) => {
  const abis = readdirSync(from, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name);

  const removed = [];

  for (const abi of abis) {
    const target = join(to, 'jniLibs', abi);
    const ours = readdirSync(join(from, abi));

    mkdirSync(target, { recursive: true });

    const stale = removeStale({
      directory: target,
      keep: (entry) => entry === CARGO_LIB || ours.includes(entry),
    });

    removed.push(...stale.map((entry) => `${abi}/${entry}`));

    cpSync(join(from, abi), target, { recursive: true });
  }

  return { abis, removed };
};

// Kotlin sources removed from the overlay have to disappear from the generated
// project too — a leftover file still compiles and can reference code that is
// no longer there.
export const copySources = ({ from, to }) => {
  const ours = readdirSync(from);

  mkdirSync(to, { recursive: true });

  removeStale({
    directory: to,
    keep: (entry) =>
      !entry.endsWith('.kt') || ours.includes(entry) || GENERATED_SOURCES.includes(entry),
  });

  cpSync(from, to, { recursive: true });

  return ours;
};

// `tauri icon` writes its own mipmaps into gen/android, so our drawables are
// merged in rather than replacing the directory.
export const copyResources = ({ from, to }) => {
  if (!existsSync(from)) {
    return [];
  }

  cpSync(from, to, { recursive: true });

  return readdirSync(from);
};
